server:
  port: 80 #服务端口

spring:
  application:
    name: cloud-consumer-order #服务名

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #      defaultZone: http://127.0.0.1:7001/eureka/ # 底板 人3
      defaultZone: http://eureka7002.com:7002/eureka/, http://eureka7001.com:7001/eureka/