server:
  port: 9527 #服务端口

spring:
  application:
    name: cloud-gateway #服务名
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #开启从注册中心动态创建路由功能，利用服务名路由
      routes:
      - id: payment_routh           #路由id,要求唯一
       # uri: http://localhost:8001  #匹配后提供服务地址
        uri: lb://cloud-payment-service  #匹配后提供服务地址
        predicates:
         - Path=/payment/get/**      #断言，路径匹配

      - id: payment_routh2
  #     uri: http://localhost:8001
        uri: lb://cloud-payment-service
        predicates:
         - Path=/payment/lb
         - After=2020-03-12T19:18:10.309+08:00[Asia/Shanghai]

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
            defaultZone: http://127.0.0.1:7001/eureka/ # 底板 人3
    #   defaultZone: http://eureka7002.com:7002/eureka/, http://eureka7001.com:7001/eureka/

