server:
  port: 80 #服务端口

spring:
  application:
    name: cloud-consumer-order #服务名

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #      defaultZone: http://127.0.0.1:7001/eureka/ # 底板 人3
      defaultZone: http://eureka7002.com:7002/eureka/, http://eureka7001.com:7001/eureka/
ribbon:
    #建立连接用时
  ReadTimeout: 5000
    #服务读取到可用资源用时
  connectTimeout: 5000
logging:
  level:
    com.teng.springcloud.service.PaymentService: debug
